fix: 🐛 disable buy now button based on operator details
Psychedelic/nft-marketplace-fe pull request #421
Opened 2022-06-30 08:16 UTC by prasanthLalapeta

## Why?

Disable buy now button based on operator details

## How?

- [ ] use operator details from token details object and disable buy now button if operator not found
- [ ] show tooltip with message `Oops! Can't be purchased, possibly because token was transferred outside Jelly marketplace to a new wallet`

## Tickets?

- [Notion ticket](the-ticket-url-here)

## Demo?

++ to be defined

2022-07-04 15:08 UTC, heldrida requested changes

2022-07-04 15:08 UTC, heldrida commented on src/utils/nfts.ts
> +export const isNFTOperatorIsMKP = (
Seems that we don't need two "is" in the name; as such, we can have a more meaningful name e.g. `isOperatorMarketplace`

```suggestion
export const isOperatorMarketplace = (
```

2022-07-04 15:08 UTC, heldrida commented on src/utils/nfts.ts
>  }) => typeof tokendId !== 'undefined' && tokenMetadataById[tokendId];
While this was written before, seems that the tokenId validation should be computed by

```
isTokenId(tokenId)
```

Which also seems that tokenId might be undefined, so the type needs to change to

```
tokenId?: string | number
```

If not, then there's no need to verify if not undefined, because otherwise seems guaranteed its always either string or number.

2022-07-04 15:08 UTC, heldrida commented on src/utils/nfts.ts
> +  return (
Any reason why we are wrapping this in ( ) ?

2022-07-04 15:08 UTC, heldrida commented on src/stitches.config.ts
> +    white: '#000000',
Here's another example of how the colours are named incorrectly; We shouldn't be naming colours by the component or feature they are part of, and also NOT name colours the opposite that they should be. For example, we'd put white where white is required in the application NOT change white to be a different tone in the source.

2022-07-05 02:47 UTC, prasanthLalapeta commented on src/utils/nfts.ts
> +  return true;
Yeah. Updated. Thanks!

2022-07-05 03:01 UTC, prasanthLalapeta commented on src/utils/nfts.ts
> +export const isNFTOperatorIsMKP = (
Yeah updated. Thanks!

2022-07-05 03:15 UTC, prasanthLalapeta commented on src/utils/nfts.ts
> +  return (
I guess it’s due to prettier. On save whole file changed. Reverting back. Thanks

2022-07-05 03:24 UTC, prasanthLalapeta commented on src/utils/nfts.ts
>  }) => typeof tokendId !== 'undefined' && tokenMetadataById[tokendId];
Updated by adding

```
tokenId?: string | number
```

Thanks

2022-07-05 03:24 UTC, prasanthLalapeta commented on src/utils/nfts.ts
> +  return (
Updated

2022-07-05 03:29 UTC, prasanthLalapeta commented on src/stitches.config.ts
> +    white: '#000000',
Yeah. Confused over naming conventions in stitches config

2022-07-05 03:49 UTC, prasanthLalapeta commented on src/stitches.config.ts
> +    white: '#000000',
Updated with `defaultTxtColour` & `defaultBackgroundColour` names

2022-07-05 10:45 UTC, heldrida approved these changes

2022-07-05 11:18 UTC, merged